fieldLayouts:
  950e4fd3-8e5b-4b6d-832e-bfaa48f6f01d:
    tabs:
      -
        elements:
          -
            instructions: null
            label: ''
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: 0d702c45-61e8-4b2a-a791-14d9ab4494f8
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 971392cb-1900-4ded-bac5-de3afbe9d78a
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 7a8242f5-c4b2-415c-9a74-80e4e2fecc69
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: header
        sortOrder: 1
handle: header
hasTitleField: true
name: header
section: 47ca034c-6a40-4bb2-9ff2-3701141f64a3
sortOrder: 1
titleFormat: null
