handle: headerCategory
name: 'header category'
siteSettings:
  4ec3f9c2-9247-4880-a799-c6ac984a10e4:
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: ef907b70-26e6-4541-8cb3-dab26e08f59f
