handle: portfoliotype
name: portfolioType
siteSettings:
  4ec3f9c2-9247-4880-a799-c6ac984a10e4:
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: 4dee0bd7-f8d2-4b12-8716-f317644d56da
