contentColumnType: text
fieldGroup: d6394e72-4d16-4bc4-b66f-32ea917e0f1a
handle: contactText
instructions: ''
name: 'Contact Text'
searchable: true
settings:
  charLimit: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
