contentColumnType: datetime
fieldGroup: afb6f9db-0786-4a4d-88ff-b8cfd08bd22d
handle: date
instructions: ''
name: date
searchable: true
settings:
  minuteIncrement: '30'
  showDate: 1
  showTime: 0
translationKeyFormat: null
translationMethod: none
type: craft\fields\Date
