contentColumnType: string(7)
fieldGroup: e8a13612-83d9-4f49-8e90-48db3f2abf46
handle: skillcolor
instructions: ''
name: skillcolor
searchable: true
translationKeyFormat: null
translationMethod: none
type: craft\fields\Color
