contentColumnType: integer(10)
fieldGroup: e8a13612-83d9-4f49-8e90-48db3f2abf46
handle: skillpercentage
instructions: ''
name: skillPercentage
searchable: true
settings:
  decimals: '0'
  max: ''
  min: '0'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
