contentColumnType: string
fieldGroup: afb6f9db-0786-4a4d-88ff-b8cfd08bd22d
handle: textPosition
instructions: ''
name: 'text position'
searchable: true
settings:
  options:
    -
      __assoc__:
        -
          - default
          - ''
        -
          - label
          - 'left text'
        -
          - value
          - fadeInLeft
    -
      __assoc__:
        -
          - default
          - ''
        -
          - label
          - 'right text'
        -
          - value
          - fadeInRight
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
