contentColumnType: text
fieldGroup: afb6f9db-0786-4a4d-88ff-b8cfd08bd22d
handle: timelineTitle
instructions: ''
name: 'timeline title'
searchable: true
settings:
  charLimit: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
