enableVersioning: true
handle: resumeExperience
name: 'resume experience'
propagationMethod: all
siteSettings:
  4ec3f9c2-9247-4880-a799-c6ac984a10e4:
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
